Feature branch
kiptubei/members-only pull request #1
Opened 2020-08-13 12:44 UTC by kiptubei

In this project, we have built an exclusive clubhouse where your members can write embarrassing posts about non-members. Inside the clubhouse, members can see who the author of a post is but, outside, they can only see the story and wonder who wrote it.

### Models Created and Associations

- Member model
- Post model

- Member model has many posts
- Post model belongs to member
`
Features 
Members can create posts, view all posts and their authors
Non-members cannot create post, can view all posts but not their members
Member and password validations
Posts validation

2020-08-13 22:32 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thanks for the job done so far.
The application is working like a charm :smiley_cat: 
However, there are just some small issues. Read the comments left below.

Once the issues solved, kindly submit a new code review request.
Thanks

Mael FOSSO

2020-08-13 22:32 UTC, maelfosso commented on app/views/posts/index.html.erb
> +</div>
`if..else` it's what we called logic.
It's not allowed in views.
Move that code in **views helpers**

2020-08-13 22:32 UTC, maelfosso commented on app/views/layouts/application.html.erb
> +<% end %>
Move logic into views helpers

2020-08-13 22:32 UTC, maelfosso commented on app/views/layouts/application.html.erb
> +<% end %>
Move that logic into view helpers

2020-08-14 00:08 UTC, OlawaleJoseph commented on app/views/layouts/application.html.erb
> +<% end %>
Fixed

2020-08-14 20:17 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team ,  you have done a brilliant job with this project. :clap:
#### You can merge  !!!

2020-08-14 22:32 UTC, merged